services:
  ai_core:
    image: manhmitcf/dat_lab_management_aicore:deploy
    container_name: dat_lab_deepstream
    runtime: nvidia
    restart: unless-stopped
    env_file:
      - ./config/.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/workspace/ai_corey.
      - ./pretrained:/workspace/ai_core/pretrained
    devices:
      # Mount USB Camera (Adjust if using CSI Camera or different USB port)
      - /dev/video0:/dev/video0
    network_mode: "host" # Crucial for high-performance UDP/RTP streaming
