# Generated by Django 4.2.11 on 2026-02-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.IntegerField(help_text='Sequential frame index')),
                ('timestamp', models.DateTimeField(help_text='UTC inference timestamp')),
                ('count_in', models.IntegerField(default=0, help_text='Cumulative count of entries')),
                ('count_out', models.IntegerField(default=0, help_text='Cumulative count of exits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ObjectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(help_text='Unique tracking ID of the object')),
                ('class_name', models.CharField(help_text='Object category/class', max_length=50)),
                ('conf', models.FloatField(help_text='Model confidence score (0-1)')),
                ('bbox', models.JSONField(help_text='Bounding box [x1, y1, x2, y2]')),
                ('coordinates', models.JSONField(help_text='Center coordinates [x, y]')),
                ('height', models.FloatField(help_text='Object height in pixels')),
                ('width', models.FloatField(help_text='Object width in pixels')),
                ('frame_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='Lab_Management.framedata')),
            ],
        ),
        migrations.AddIndex(
            model_name='framedata',
            index=models.Index(fields=['timestamp'], name='Lab_Managem_timesta_d1eab0_idx'),
        ),
    ]
