# Generated by Django 4.2.11 on 2026-02-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdetection',
            name='frame_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='Lab_Management.framedata'),
        ),
    ]
