# Generated by Django 4.2.11 on 2026-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0002_alter_objectdetection_frame_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdetection',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='objectdetection',
            name='height',
        ),
        migrations.RemoveField(
            model_name='objectdetection',
            name='width',
        ),
        migrations.AddField(
            model_name='framedata',
            name='alert',
            field=models.BooleanField(default=False, help_text='Alert flag for abnormal events'),
        ),
        migrations.AddField(
            model_name='framedata',
            name='height_2D',
            field=models.IntegerField(blank=True, help_text='Height of the 2D map', null=True),
        ),
        migrations.AddField(
            model_name='framedata',
            name='height_frame',
            field=models.IntegerField(blank=True, help_text='Height of the original frame', null=True),
        ),
        migrations.AddField(
            model_name='framedata',
            name='width_2D',
            field=models.IntegerField(blank=True, help_text='Width of the 2D map', null=True),
        ),
        migrations.AddField(
            model_name='framedata',
            name='width_frame',
            field=models.IntegerField(blank=True, help_text='Width of the original frame', null=True),
        ),
        migrations.AddField(
            model_name='objectdetection',
            name='coordinates_2D',
            field=models.JSONField(blank=True, help_text='[x, y] center projected onto 2D map', null=True),
        ),
        migrations.AlterField(
            model_name='objectdetection',
            name='bbox',
            field=models.JSONField(help_text='[x1, y1, x2, y2] in pixels'),
        ),
        migrations.AlterField(
            model_name='objectdetection',
            name='class_name',
            field=models.CharField(help_text='Object class name', max_length=50),
        ),
        migrations.AlterField(
            model_name='objectdetection',
            name='track_id',
            field=models.IntegerField(help_text='Unique tracking ID'),
        ),
    ]
