# Generated by Django 4.2.11 on 2026-03-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0003_remove_objectdetection_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framedata',
            name='frame_id',
        ),
        migrations.RemoveField(
            model_name='objectdetection',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='objectdetection',
            name='conf',
        ),
    ]
