# Generated by Django 4.2.11 on 2026-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0004_remove_framedata_frame_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framedata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='framedata',
            name='alert',
            field=models.CharField(choices=[('none', 'None'), ('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='none', help_text='Alert level (none, info, warning, critical)', max_length=10),
        ),
    ]
