# Generated by Django 4.2.11 on 2026-03-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0005_remove_framedata_created_at_alter_framedata_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this calibration was created.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('point', 'Point'), ('line', 'Line')], help_text="'point' or 'line'", max_length=5)),
                ('camera', models.JSONField(help_text='Array of [x, y] coordinates on the camera frame.')),
                ('floor_plan', models.JSONField(help_text='Array of [x, y] coordinates on the floor plan.')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='Lab_Management.calibration')),
            ],
        ),
    ]
