# Generated by Django 4.2.11 on 2026-03-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0006_calibration_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('camera', models.JSONField(help_text='[x, y] coordinates on the camera frame.')),
                ('map', models.JSONField(help_text='[x, y] coordinates on the floor plan.')),
            ],
        ),
        migrations.CreateModel(
            name='CountingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_start', models.JSONField(help_text='[x, y] start of line')),
                ('line_end', models.JSONField(help_text='[x, y] end of line')),
                ('inside_point', models.JSONField(help_text="[x, y] point indicating 'inside'")),
                ('crossing_margin', models.FloatField()),
                ('frame_width', models.IntegerField(blank=True, null=True)),
                ('frame_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calibration',
            name='image_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='image_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='map_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='map_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='calibration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='Lab_Management.calibration'),
        ),
    ]
