# Generated by Django 4.2.11 on 2026-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_Management', '0007_correspondence_countingsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedata',
            name='fps',
            field=models.FloatField(blank=True, help_text='Processing FPS', null=True),
        ),
        migrations.AddField(
            model_name='framedata',
            name='occupancy',
            field=models.IntegerField(default=0, help_text='Current occupancy'),
        ),
    ]
