name: Deploy to Edge Jetson

on:
  push:
    branches:
      - aicore/deploy_jetson

jobs:
  build-and-deploy:
    # Use Self-hosted runner to run directly on the Jetson hardware
    runs-on: [self-hosted, deploy]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Sync Source Code to Desktop Directory
        run: |
          echo "Syncing new project files directly to ~/Desktop/DAT_Lab-Management (keeping models and envs safe)..."
          rsync -av --exclude '.git' --exclude 'ai_core/pretrained' --exclude 'ai_core/config/.env' ./ ~/Desktop/DAT_Lab-Management/

      - name: Build Docker Image on Jetson
        run: |
          echo "Building Docker Image inside the Desktop path..."
          cd ~/Desktop/DAT_Lab-Management/ai_core
          docker build -t manhmitcf/dat_lab_management_aicore:deploy .

      - name: Deploy with Docker Compose
        run: |
          echo "Restarting services with the new image..."
          cd ~/Desktop/DAT_Lab-Management/ai_core
          docker-compose down
          docker-compose up -d

      - name: Clean up old Docker Images
        run: |
          echo "Cleaning up dangling images to free up disk space..."
          docker image prune -f
