name: Deploy Django Backend to Azure

on:
  push:
    branches: [ "feature/azure-deploy" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          DOCKER_IMAGE=manhmitcf/dat_lab_management_backend
          docker build backend -t $DOCKER_IMAGE:deploy
          docker push $DOCKER_IMAGE:deploy

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DAT_Lab_Management'
          images: 'manhmitcf/dat_lab_management_backend:deploy'